import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto_slab = Roboto_Slab({
  weight: ["300", "400", "500", "600", "700"], // Include various weights
  subsets: ["latin", "greek"], // Include Latin and Greek subsets
  display: "swap", // Use 'swap' for better font loading performance
  variable: "--font-roboto-slab", // Define the CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto_slab.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
